// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: line_items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO line_items(
    id,
    user_id,
    plan_id,
    plan_category_id,
    description,
    deposit,
    withdrawl,
    created_at,
    updated_at
)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING id, user_id, plan_id, plan_category_id, description, deposit, withdrawl, created_at, updated_at
`

type CreateLineItemParams struct {
	UserID         uuid.UUID
	PlanID         uuid.UUID
	PlanCategoryID uuid.UUID
	Description    string
	Deposit        int32
	Withdrawl      int32
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, createLineItem,
		arg.UserID,
		arg.PlanID,
		arg.PlanCategoryID,
		arg.Description,
		arg.Deposit,
		arg.Withdrawl,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.PlanCategoryID,
		&i.Description,
		&i.Deposit,
		&i.Withdrawl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLineItems = `-- name: GetLineItems :many
SELECT id, user_id, plan_id, plan_category_id, description, deposit, withdrawl, created_at, updated_at
FROM line_items
WHERE plan_id = $1
`

func (q *Queries) GetLineItems(ctx context.Context, planID uuid.UUID) ([]LineItem, error) {
	rows, err := q.db.QueryContext(ctx, getLineItems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LineItem
	for rows.Next() {
		var i LineItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.PlanCategoryID,
			&i.Description,
			&i.Deposit,
			&i.Withdrawl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
