// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type LineItem struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PlanCategoryID uuid.UUID
	Description    string
	Deposit        int32
	Withdrawal     int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Plan struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlanCategory struct {
	ID         uuid.UUID
	PlanID     uuid.UUID
	Name       string
	Deposit    int32
	Withdrawal int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	FirstName      string
	LastName       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
