// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const resetLineItems = `-- name: ResetLineItems :exec
DELETE FROM line_items
`

func (q *Queries) ResetLineItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetLineItems)
	return err
}

const resetPlanCategories = `-- name: ResetPlanCategories :exec
DELETE FROM plan_categories
`

func (q *Queries) ResetPlanCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPlanCategories)
	return err
}

const resetPlans = `-- name: ResetPlans :exec
DELETE FROM plans
`

func (q *Queries) ResetPlans(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPlans)
	return err
}

const resetRefreshTokens = `-- name: ResetRefreshTokens :exec
DELETE FROM refresh_tokens
`

func (q *Queries) ResetRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRefreshTokens)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
